name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    name: Deploy to Github Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the project
        id: deployment
        uses: actions/deploy-pages@v1
