name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Deploy to Github Pages
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build.yml
      - name: Deploy the project
        id: deployment
        uses: actions/deploy-pages@v1
